_target_: concdvae.pl_modules.decoder.GemNetTDecoder
hidden_dim: 128
latent_dim: ${model.latent_dim}
time_emb_dim: ${model.time_emb_dim}
max_neighbors: ${model.max_neighbors}
radius: ${model.radius}
scale_file: ${oc.env:PROJECT_ROOT}/concdvae/pl_modules/gemnet/gemnet-dT.json
